
package main.java.webservice.jax.wsimport.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StringHelper", targetNamespace = "http://service.wsimport.jax.webservice.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StringHelper {


    /**
     * 
     * @param str2
     * @param str1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "contactResult", targetNamespace = "")
    @RequestWrapper(localName = "contact", targetNamespace = "http://service.wsimport.jax.webservice.java.com/", className = "com.java.webservice.jax.wsimport.client.Contact")
    @ResponseWrapper(localName = "contactResponse", targetNamespace = "http://service.wsimport.jax.webservice.java.com/", className = "com.java.webservice.jax.wsimport.client.ContactResponse")
    @Action(input = "http://service.wsimport.jax.webservice.java.com/StringHelper/contactRequest", output = "http://service.wsimport.jax.webservice.java.com/StringHelper/contactResponse")
    public String contact(
        @WebParam(name = "str1", targetNamespace = "")
        String str1,
        @WebParam(name = "str2", targetNamespace = "")
        String str2);

}
