
package webservice.jax.wsimport.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "StringHelperImplService", targetNamespace = "http://service.wsimport.jax.webservice.java.com/", wsdlLocation = "http://localhost:7777/sh?wsdl")
public class StringHelperImplService
        extends Service {

    private final static URL STRINGHELPERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STRINGHELPERIMPLSERVICE_EXCEPTION;
    private final static QName STRINGHELPERIMPLSERVICE_QNAME = new QName("http://service.wsimport.jax.webservice.java.com/", "StringHelperImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/sh?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STRINGHELPERIMPLSERVICE_WSDL_LOCATION = url;
        STRINGHELPERIMPLSERVICE_EXCEPTION = e;
    }

    public StringHelperImplService() {
        super(__getWsdlLocation(), STRINGHELPERIMPLSERVICE_QNAME);
    }

    public StringHelperImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STRINGHELPERIMPLSERVICE_QNAME, features);
    }

    public StringHelperImplService(URL wsdlLocation) {
        super(wsdlLocation, STRINGHELPERIMPLSERVICE_QNAME);
    }

    public StringHelperImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STRINGHELPERIMPLSERVICE_QNAME, features);
    }

    public StringHelperImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StringHelperImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns StringHelper
     */
    @WebEndpoint(name = "StringHelperImplPort")
    public StringHelper getStringHelperImplPort() {
        return super.getPort(new QName("http://service.wsimport.jax.webservice.java.com/", "StringHelperImplPort"), StringHelper.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns StringHelper
     */
    @WebEndpoint(name = "StringHelperImplPort")
    public StringHelper getStringHelperImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wsimport.jax.webservice.java.com/", "StringHelperImplPort"), StringHelper.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STRINGHELPERIMPLSERVICE_EXCEPTION != null) {
            throw STRINGHELPERIMPLSERVICE_EXCEPTION;
        }
        return STRINGHELPERIMPLSERVICE_WSDL_LOCATION;
    }

}
